### ISSUE TITLE
Distance Data Source stream name is erroneously named "AppleWeightDataSource"

### ISSUE THREAD

**Issue by theorician** [hermanmaritz/AppleHealth2GoogleFit#1]
Looks like you have a copy and paste error in your code. See 

https://github.com/hermanmaritz/AppleHealth2GoogleFit/blob/master/GoogleFitness.py#L113

It should probably be `AppleDistanceDataSource`.

Thanks for the script!

**Comment by hermuxo** [comment]
Thanks. Fixed.
https://github.com/hermanmaritz/AppleHealth2GoogleFit/commit/0979c98c7d019a5e533e6e0bd9e66995a76f31b8
